### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/be-tab-d#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up and login to account
## 📐 Functionality

The user will be introduced to the welcome page where they can either signup or login.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/116613246/220240371-4d7150c9-a1a6-4028-a511-53b49bb840fc.png)
![image](https://user-images.githubusercontent.com/116613246/220240440-3cc3785c-69d8-41ed-8cfb-535bd084d68d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ... create table of user names.
- [x] Update `data.sql` to ... users storing username and hashed password

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... take username and password and post it into the sql
- [x] Create a component to ... hash the password when signed up
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ... take the login information
- [x] Update component to ... give client confirmation permissions

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] add blur and cursor tracking blob
- [x] Make navbar for mobile
  - [x] Add the correct anchors for the different tabs 
  - [x] make the navbar for desktop
- [x] Add page content to fade in per text content. 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
