### ISSUE TITLE
Feature: User can upload CSV file

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/be-tab-d#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Upload can upload CSV file to be updated into the database.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user after signing up will have their user ID be the point to which CSV files are stored. from there, the csv files will be uploaded to different tables according to the tableType they choose.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ... have more created tables including teachers, students and courses just for this feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... sign in and retrieve their User ID.
- [x] Listen on the form hash route for uploads to insert into the schema.sql the User ID, files, description, and tabletype.
- [x] After the files are uploaded, get the headers and make sql variable for an added database query to upload to specified tabletype in database.
  - [x] parse files from upload. 
    - [x] grab files from upload
    - [x] separate comma separated values per new line into arrays lengthed by amount of rows
    - [x] separate comma separated values within each index of arrays.
  - [x] grab fileID created from upload
  - [x] grab tabletype from upload.
  - [x] create SQL to input correct data to correct tabletype, csv lists and render per row index.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ... take in user description, tabletype, and file for insert into the schema.sql

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
